spring:
  datasource:
    url: ${DATASOURCE_URI:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:sa}
    sql-script-encoding: utf-8
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  data.rest.basePath: /api
server:
  port: 8090

